title: Humble Pied
subtitle: "One inspiring creative sharing one piece of advice, all over video chat."
description: "One inspiring creative sharing one piece of advice, all over video chat."

author: Mig Reyes
github: http://github.com/migreyes/humblepied
instagram: http://instagram.com/migreyes
twitter: http://twitter.com/migreyes

# Compile Settings
source:      _source
destination: public
exclude:     [public, Gemfile, Gemfile.lock, Rakefile, README.md]

markdown:  rdiscount
permalink: /:categories/:title/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      title: "Mig Reyes, Design Director at Sprout Social"
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"


plugins:
  - jekyll-coffeescript

sass:
  style:    :compressed
  sass_dir: assets/stylesheets